### ISSUE TITLE
Message access pop-up appears even after aborting.

### ISSUE THREAD

**Issue by Amith-B** [WICG/web-otp#58]
When using a web OTP with windows.navigator the popup to access newly received message appears, it is fine. But this popup appears even after aborting the abortcontroller.

Try hitting submit without sending sms , this aborts controller, now send sms, the popup still appears.
[Stackblitz example](https://stackblitz.com/edit/js-flbjc3?file=index.js)

Steps to reproduce:

1. Start listening for the OTP through credentials.get 
```
const abortController = new AbortController();

const otpConfig = {
  otp: { transport: ['sms'] },
  signal: abortController.signal
};

credentials.get(otpConfig).then(<some more code>)
.......
``` 
2. Then abort the controller in setTimeout
`abortController.abort()`
3. Now send the sms after the controller is aborted, the message access pop-up still appears.

**Comment by agektmr** [comment]
@Amith-B If you are filing an implementation bug on Chrome rather than a spec bug, please file it at http://crbug.com/

**Comment by Amith-B** [comment]
Thanks for clarification. Have raised the bug in crbug.com.

[https://bugs.chromium.org/p/chromium/issues/detail?id=1325206](url)
